### ISSUE TITLE
Coquilles

### ISSUE THREAD

**Issue by Bambichon** [capi-83/adminTourdecom#11]
Sur le Dashboard : Membres désactivÉS / Membres actifS
Dans la sidebar : Ajouter un utilisateur (sans s)

**Comment by capi-83** [comment]
Ouai j'écrit français comme une vache allemande 🗡️ , je ferait une pr la dessus ce soir, et je te tient au jus :)

**Comment by capi-83** [comment]
Correction ok :) Merci
